# ==================================================
# Script réalisé par Spiralyfox
# Discord : @Spiralyfox
# Des idées de Skripts ? Besoin d’un script spécifique ?
# Contactez-moi sur Discord pour contribuer à la communauté.
# ==================================================

options:
    # ==================================================
    # Général
    # ==================================================
    prefix: &b[Server name] &8» &r

    # ==================================================
    # Permissions
    # ==================================================
    perm_feed: spiralyskript.feed.feed

command /feed:
    permission: {@perm_feed}
    trigger:
        set player's food level to 20
        set player's saturation to 20
        send "{@prefix}&aVous avez été nourri complètement." to player
