# ==================================================
# Script réalisé par Spiralyfox
# Discord : @Spiralyfox
# Des idées de Skripts ? Besoin d’un script spécifique ?
# Contactez-moi sur Discord pour contribuer à la communauté.
# ==================================================

options:
    # ==================================================
    # Général
    # ==================================================
    prefix: &b[Server name] &8» &r

    # ==================================================
    # Permissions
    # ==================================================
    perm_craft: spiralyskript.craft.craft

command /craft:
    permission: {@perm_craft}
    trigger:
        open crafting table to player
