# ==================================================
# Script réalisé par Spiralyfox
# Discord : @Spiralyfox
# Des idées de Skripts ? Besoin d’un script spécifique ?
# Contactez-moi sur Discord pour contribuer à la communauté.
# ==================================================

options:
    # ==================================================
    # Général
    # ==================================================
    prefix: &b[Server name] &8» &r

    # ==================================================
    # Permissions
    # ==================================================
    perm_sun: spiralyskript.sun.sun

command /sun:
    permission: {@perm_sun}
    trigger:
        set client weather of player to sun
        send "{@prefix}Le soleil brille à nouveau !"
