# ==================================================
# Script made by Spiralyfox
# Discord : @Spiralyfox
# Script ideas ? Need a specific Skript ?
# Contact me on Discord to contribute to the community.
# ==================================================

options:
    # ==================================================
    # General
    # ==================================================
    prefix: &b[Server name] &8» &r

    # ==================================================
    # Permissions
    # ==================================================
    perm_fly: spiralyskript.fly.fly

    # ==================================================
    # Messages
    # ==================================================
    msg_fly_enable: &aYou can now fly.
    msg_fly_disable: &cFly mode is disabled.
    msg_no_fall: &eNo fall damage because fly mode is enabled.

command /fly:
    permission: {@perm_fly}
    trigger:
        if {fly-%player's uuid%} is not set:
            send "{@prefix}{@msg_fly_enable}" to player
            set player's flight mode to true
            set {fly-%player's uuid%} to true
        else:
            send "{@prefix}{@msg_fly_disable}" to player
            set player's flight mode to false
            delete {fly-%player's uuid%}

on damage:
    damage cause is fall
    victim is a player
    if {fly-%victim's uuid%} is set:
        cancel event
        send "{@prefix}{@msg_no_fall}" to victim

on quit:
    if {fly-%player's uuid%} is set:
        set player's flight mode to false
        delete {fly-%player's uuid%}
